a = 0
try:
  raise Exception('Hello, World!')
finally:
  a = 1
